package com.sybiload.shopp;

import android.content.Context;

import java.util.ArrayList;

public class Static
{
    public static ArrayList<List> allList = new ArrayList<List>();

    public static int[] defaultItemIcon = {
            R.drawable.item_apple,
            R.drawable.item_aubergine,
            R.drawable.item_bacon,
            R.drawable.item_banana,
            R.drawable.item_beans,
            R.drawable.item_beer,
            R.drawable.item_bone,
            R.drawable.item_bread,
            R.drawable.item_broccoli,
            R.drawable.item_cake,
            R.drawable.item_candy,
            R.drawable.item_carrot,
            R.drawable.item_cereal,
            R.drawable.item_cheese,
            R.drawable.item_cherry,
            R.drawable.item_chili,
            R.drawable.item_chocolate,
            R.drawable.item_clam,
            R.drawable.item_cocktail,
            R.drawable.item_coffee,
            R.drawable.item_coffee_bean,
            R.drawable.item_cola,
            R.drawable.item_cookie,
            R.drawable.item_corn,
            R.drawable.item_croissant,
            R.drawable.item_cucumber,
            R.drawable.item_donut,
            R.drawable.item_egg,
            R.drawable.item_fish,
            R.drawable.item_fried_egg,
            R.drawable.item_fries,
            R.drawable.item_garlic,
            R.drawable.item_grape,
            R.drawable.item_hamburger,
            R.drawable.item_herb,
            R.drawable.item_honey,
            R.drawable.item_hotdog,
            R.drawable.item_ice_cream,
            R.drawable.item_lemon,
            R.drawable.item_lemonade,
            R.drawable.item_lettuce,
            R.drawable.item_meat,
            R.drawable.item_melon,
            R.drawable.item_milk,
            R.drawable.item_muffin,
            R.drawable.item_mushroom,
            R.drawable.item_oil,
            R.drawable.item_orange,
            R.drawable.item_paper,
            R.drawable.item_pasta,
            R.drawable.item_pear,
            R.drawable.item_pepper,
            R.drawable.item_pepper_bis,
            R.drawable.item_pineapple,
            R.drawable.item_pizza,
            R.drawable.item_potatoe,
            R.drawable.item_poultry,
            R.drawable.item_prawn,
            R.drawable.item_pretzel,
            R.drawable.item_pumpkin,
            R.drawable.item_raisin,
            R.drawable.item_wine_red,
            R.drawable.item_salt,
            R.drawable.item_sausage,
            R.drawable.item_soup,
            R.drawable.item_squid,
            R.drawable.item_strawberry,
            R.drawable.item_sushi,
            R.drawable.item_taco,
            R.drawable.item_tea,
            R.drawable.item_toast,
            R.drawable.item_tomatoe,
            R.drawable.item_vanilla,
            R.drawable.item_vinegar,
            R.drawable.item_washing_liquid,
            R.drawable.item_water,
            R.drawable.item_wine_white,
    };
}
